import React, { useEffect, useState, useCallback } from 'react';
import { Sparkles, RefreshCw, Zap, CheckCircle } from 'lucide-react';
import { Card, Button } from '../../components';
import { getLatestRecommendation, refreshRecommendation, type Recommendation } from '../../services';

export const Recommendations: React.FC = () => {
  const [recommendation, setRecommendation] = useState<Recommendation | null>(null);
  const [loading, setLoading] = useState(true);

  const fetchRecommendation = useCallback(async (isRefresh = false) => {
    if (isRefresh) setLoading(true);
    try {
      const data = await getLatestRecommendation();
      setRecommendation(data);
    } catch (error) {
      console.error('Failed to fetch recommendation', error);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    let ignore = false;
    const init = async () => {
      const data = await getLatestRecommendation();
      if (!ignore) {
        setRecommendation(data);
        setLoading(false);
      }
    };
    init();
    return () => { ignore = true; };
  }, []);

  const handleRefresh = async () => {
    setLoading(true);
    try {
      const data = await refreshRecommendation();
      setRecommendation(data);
    } catch (error) {
      console.error('Failed to refresh recommendation', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <section className="section-light" style={{ minHeight: '80vh', backgroundColor: 'var(--bg-secondary)' }}>
      <div className="container">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 'var(--space-4)', borderBottom: '2px solid rgba(0, 0, 0, 0.05)', paddingBottom: 'var(--space-2)' }}>
           <div>
             <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
               <Sparkles size={24} color="var(--color-mongo-green)" />
               <h2 style={{ margin: 0 }}>Smart Recommendations</h2>
             </div>
             <p style={{ color: 'var(--text-secondary)', fontSize: 'var(--font-size-caption)', marginTop: '4px' }}>
               AI-driven insights based on real-time sensor data and historical trends
             </p>
           </div>
           <div style={{ display: 'flex', gap: 'var(--space-2)' }}>
             <Button variant="outlined" onClick={() => fetchRecommendation(true)} size="small" style={{ display: 'flex', gap: '4px' }}>
               <RefreshCw size={14} /> Sync
             </Button>
             <Button variant="primary" onClick={handleRefresh} size="small" style={{ display: 'flex', gap: '4px' }}>
               <Zap size={14} /> New Insight
             </Button>
           </div>
        </div>

        {loading ? (
          <div style={{ textAlign: 'center', padding: 'var(--space-10)' }}>
            <p>Analyzing system telemetry...</p>
          </div>
        ) : recommendation ? (
          <Card padding="large" elevation="standard" style={{ borderTop: '4px solid var(--color-mongo-green)' }}>
            <div style={{ display: 'flex', gap: 'var(--space-3)' }}>
              <div style={{ flexShrink: 0, width: '48px', height: '48px', borderRadius: '12px', background: 'rgba(0, 237, 100, 0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <Sparkles color="var(--color-mongo-green)" size={24} />
              </div>
              <div style={{ flex: 1 }}>
                <p className="tech-label" style={{ marginBottom: 'var(--space-1)', display: 'inline-block' }}>INTELLIGENT ANALYSIS</p>
                <h3 style={{ margin: '0 0 12px 0', fontSize: 'var(--font-size-h2)' }}>Recommendation for Optimization</h3>
                <p style={{ fontSize: 'var(--font-size-body-large)', lineHeight: '1.6', color: 'var(--text-primary)', marginBottom: 'var(--space-3)' }}>
                  {recommendation.message}
                </p>
                <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-1)', color: 'var(--color-cool-gray)', fontSize: '10px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                  <span>Generated by SmartAgri AI</span>
                  <span>•</span>
                  <span>{new Date(recommendation.created_at).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}</span>
                </div>
              </div>
            </div>
          </Card>
        ) : (
          <Card elevation="subtle" padding="large" style={{ textAlign: 'center' }}>
            <div style={{ marginBottom: 'var(--space-2)' }}>
              <CheckCircle size={48} color="var(--color-mongo-green)" style={{ opacity: 0.5 }} />
            </div>
            <h3 style={{ margin: '0 0 8px 0' }}>System Fully Optimized</h3>
            <p style={{ color: 'var(--text-secondary)' }}>Everything is running perfectly. No new recommendations needed at this time.</p>
          </Card>
        )}

        <div style={{ marginTop: 'var(--space-8)' }}>
          <h3 style={{ fontSize: 'var(--font-size-body)', color: 'var(--color-cool-gray)', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: 'var(--space-3)' }}>
            How it works
          </h3>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: 'var(--space-3)' }}>
            <Card elevation="none" padding="standard" style={{ background: 'transparent', border: '1px dashed var(--border-color)' }}>
              <h4 style={{ margin: '0 0 8px 0' }}>1. Data Collection</h4>
              <p style={{ fontSize: 'var(--font-size-caption)', color: 'var(--text-secondary)' }}>We aggregate live telemetry from all connected sensors across your facility.</p>
            </Card>
            <Card elevation="none" padding="standard" style={{ background: 'transparent', border: '1px dashed var(--border-color)' }}>
              <h4 style={{ margin: '0 0 8px 0' }}>2. Pattern Analysis</h4>
              <p style={{ fontSize: 'var(--font-size-caption)', color: 'var(--text-secondary)' }}>Our algorithms compare current readings against ideal growth thresholds.</p>
            </Card>
            <Card elevation="none" padding="standard" style={{ background: 'transparent', border: '1px dashed var(--border-color)' }}>
              <h4 style={{ margin: '0 0 8px 0' }}>3. Actionable Insights</h4>
              <p style={{ fontSize: 'var(--font-size-caption)', color: 'var(--text-secondary)' }}>Receive direct advice on how to adjust your hardware to maximize yield.</p>
            </Card>
          </div>
        </div>
      </div>
    </section>
  );
};
